version: "3.1"
services:
  mysql:
    image: mariadb:latest 
    container_name: portal_pacientes_db
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: <database_name>
      MYSQL_USER: <user>
      MYSQL_PASSWORD: <password>
    restart: always
    ports:
      - 3306:3306
    volumes:
      - portal_db_volume:/var/lib/mysql
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# ------
#   DEV
# ------
  app:
    # build: .
    image: eamanu/portal_paciente:main
    container_name: portal_pacientes_app
    env_file:
      - .env_backend
    restart: always
    depends_on:
      - mysql
    ports:
      - 8000:8000

  frontend:
    image: eamanu/portal_paciente_frontend:main
    container_name: portal_pacientes_frontend
    restart: always
    depends_on:
      - app
    ports:
      - 81:80
# --------
# TEST/PROD
# --------
  app_test:
    # build: .
    image: eamanu/portal_paciente:main
    container_name: portal_pacientes_app_test
    env_file:
      - .env_backend_test
    restart: always
    depends_on:
      - mysql
    ports:
      - 8001:8000

  frontend_test:
    image: eamanu/portal_paciente_frontend:main
    container_name: portal_pacientes_frontend_test
    restart: always
    depends_on:
      - app
    ports:
      - 80:80

volumes:
  portal_db_volume:
